---

# Versions for the python packages that are installed
pip_version_pip: latest
pip_version_setuptools: latest
pip_version_six: "{{__pip_version_six}}"
pip_version_docker_py: "{{__pip_version_docker_py}}"
pip_extra_args: "{{__pip_extra_args}}"

proxy: no
proxy_url: "http://{{__proxy_login}}:{{__proxy_password}}@{{__proxy_host}}:{{__proxy_port}}"
no_proxy: "{{__no_proxy}}"
